In [1]:
import numpy as np

In [3]:
A=np.array([[1,2,3],[4,5,6]])

In [4]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
A.ndim

2

In [6]:
A.shape


(2, 3)

In [7]:
A.size

6

In [9]:
A.dtype

dtype('int64')

In [11]:
#slicing

A[1,1:3]

array([5, 6])

In [13]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
B[1:, 2]

array([6, 9])

In [17]:
A=np.arange(1,10)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
A[1:7:2]

array([2, 4, 6])

In [20]:
B[:,0]+B[:,1]

array([ 3,  9, 15])

In [22]:
#built in method: sum along the rows while invoking axis=0
#can be axis=1 if sum along columns or axis=2 if sum along depth

np.sum(B, axis=1)

array([ 6, 15, 24])

In [23]:
import pandas as pd

In [25]:
pd.Series(data=[[1,2,"t1"],[3,4,"t2"],[5,6,"t3"]],index=["col1","col2", "col3"])

col1    [1, 2, t1]
col2    [3, 4, t2]
col3    [5, 6, t3]
dtype: object

In [26]:
df=pd.read_csv("countries.csv")

In [ ]:
pd.read_csv

In [27]:
df.head(5)

Country                               Region  Population  \
0     Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1         Albania   EASTERN EUROPE                          3581655   
2         Algeria   NORTHERN AFRICA                        32930091   
3  American Samoa   OCEANIA                                   57794   
4         Andorra   WESTERN EUROPE                            71201   

   Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
0          647500                       48,0                         0,00   
1           28748                      124,6                         1,26   
2         2381740                       13,8                         0,04   
3             199                      290,4                        58,29   
4             468                      152,1                         0,00   

  Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
0         23,06                             163,07               700.0   
1         -4,93                              21,52              4500.0   
2         -0,39                                 31              6000.0   
3        -20,71                               9,27              8000.0   
4           6,6                               4,05             19000.0   

  Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
0         36,0               3,2      12,13      0,22     87,65       1   
1         86,5              71,2      21,09      4,42     74,49       3   
2         70,0              78,1       3,22      0,25     96,53       1   
3         97,0             259,5         10        15        75       2   
4        100,0             497,2       2,22         0     97,78       3   

  Birthrate Deathrate Agriculture Industry Service  
0      46,6     20,34        0,38     0,24    0,38  
1     15,11      5,22       0,232    0,188   0,579  
2     17,14      4,61       0,101      0,6   0,298  
3     22,46      3,27         NaN      NaN     NaN  
4      8,71      6,25         NaN      NaN     NaN

In [28]:
df.dtypes

Country                                object
Region                                 object
Population                              int64
Area (sq. mi.)                          int64
Pop. Density (per sq. mi.)             object
Coastline (coast/area ratio)           object
Net migration                          object
Infant mortality (per 1000 births)     object
GDP ($ per capita)                    float64
Literacy (%)                           object
Phones (per 1000)                      object
Arable (%)                             object
Crops (%)                              object
Other (%)                              object
Climate                                object
Birthrate                              object
Deathrate                              object
Agriculture                            object
Industry                               object
Service                                object
dtype: object

In [30]:
df.isnull().sum()

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [34]:
df.describe().round()

Population  Area (sq. mi.)  GDP ($ per capita)
count  2.270000e+02           227.0               226.0
mean   2.874028e+07        598227.0              9690.0
std    1.178913e+08       1790282.0             10049.0
min    7.026000e+03             2.0               500.0
25%    4.376240e+05          4648.0              1900.0
50%    4.786994e+06         86600.0              5550.0
75%    1.749777e+07        441811.0             15700.0
max    1.313974e+09      17075200.0             55100.0

In [35]:
df.loc[0:5, ["Region", "Population"]]

Region  Population
0        ASIA (EX. NEAR EAST)             31056997
1  EASTERN EUROPE                          3581655
2  NORTHERN AFRICA                        32930091
3  OCEANIA                                   57794
4  WESTERN EUROPE                            71201
5  SUB-SAHARAN AFRICA                     12127071