In [1]:
import numpy as np

In [3]:
A=np.array([[1,2,3],[4,5,6]])

In [4]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
A.ndim

2

In [6]:
A.shape


(2, 3)

In [7]:
A.size

6

In [9]:
A.dtype

dtype('int64')

In [11]:
#slicing

A[1,1:3]

array([5, 6])

In [13]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
B[1:, 2]

array([6, 9])

In [17]:
A=np.arange(1,10)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
A[1:7:2]

array([2, 4, 6])

In [20]:
B[:,0]+B[:,1]

array([ 3,  9, 15])

In [22]:
#built in method: sum along the rows while invoking axis=0
#can be axis=1 if sum along columns or axis=2 if sum along depth

np.sum(B, axis=1)

array([ 6, 15, 24])